"""Initial Keystone schema: landing, staging, identity, invariants, review, ops.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-22

Hand-written, not autogenerated. Notes on the choices that are load-bearing
rather than incidental:

* **Extensions.** ``vector`` (incident similarity) and ``pgcrypto`` (SQL-side
  digest, used by the schema tests to cross-check the API-key hashing scheme)
  are created here, so ``alembic upgrade head`` on a *completely empty*
  database is sufficient. ``infra/initdb`` also creates them on first boot;
  both are ``IF NOT EXISTS``.

* **No unique key on ``(generation, natural_key)`` in the ``stg_*`` tables.**
  Staging mirrors what a source actually emitted, and the conflict catalogue
  requires duplicates to be *representable*: C11 is literally "the same
  ``payment_id`` twice in one generation". A unique constraint there would make
  the mandated conflict unstorable, so those are plain indexes.

* **``entity_links``/``field_lineage`` carry ``canonical_id`` without a foreign
  key to ``entities``.** ``canonical_id`` is a deterministic uuid5 of the sorted
  source refs, computed by entity resolution; the canonical row itself is
  written by a *different database role* (``apply_writer``) in a different
  transaction. A physical FK would force the detection path to hold a privilege
  it is deliberately denied. The link is logical and stable by construction.

* **Money is integer, never float.** Budget and audit costs are ``microusd``
  (bigint). Domain money keeps the ``amount_cents`` integer the seed contract
  pins, and each such column carries a stored generated ``*_microusd`` sibling
  (1 cent = 10000 microusd) so both units are queryable and can never drift.
  The CRM deal amount arrives as a CRM-shaped float; staging keeps it verbatim
  as text (``amount_raw``) and normalizes to integer cents.

* **``entities`` UPDATE requires a same-transaction ``proposal_events`` row.**
  A deferred constraint trigger enforces the design rule that the apply path
  writes its reversal record in the same transaction as the canonical write.
  Grants say *who* may update the canonical layer; this trigger says *how*.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


class Vector(sa.types.UserDefinedType):
    """pgvector ``vector`` column, dimension deliberately unpinned.

    ``docs/DESIGN.md`` specifies ``incidents(id, centroid vector, label)`` with
    no dimension, and the embedding provider is switchable (mock / voyage /
    openai) with different widths. The ANN index lands with the provider.
    """

    cache_ok = True

    def get_col_spec(self, **kw: object) -> str:
        return "vector"


PROPOSAL_STATUS = ("pending", "approved", "rejected", "applied", "rolled_back", "sensitive_hold")
CONFLICT_STATUS = ("open", "escalated", "resolved", "dismissed")
INVARIANT_VERDICT = ("pass", "fail", "unchecked")
INGEST_STATUS = ("running", "ok", "failed", "partial")
API_CLIENT_SCOPE = ("client", "admin")

ENUMS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("proposal_status", PROPOSAL_STATUS),
    ("conflict_status", CONFLICT_STATUS),
    ("invariant_verdict", INVARIANT_VERDICT),
    ("ingest_status", INGEST_STATUS),
    ("api_client_scope", API_CLIENT_SCOPE),
)

TABLES = (
    "conflict_incidents",
    "incidents",
    "api_clients",
    "audit_log",
    "budget_ledger",
    "proposal_events",
    "proposals",
    "conflicts",
    "invariant_results",
    "field_lineage",
    "entity_link_candidates",
    "entity_links",
    "entities",
    "stg_payment",
    "stg_enrollment",
    "stg_student",
    "stg_crm_deal",
    "stg_crm_contact",
    "raw_records",
    "ingest_runs",
)

JSONB = postgresql.JSONB
TS = sa.TIMESTAMP(timezone=True)
NOW = sa.text("now()")


def _enum(name: str, values: tuple[str, ...]) -> postgresql.ENUM:
    """Reference an enum type created up-front (never re-created per column)."""
    return postgresql.ENUM(*values, name=name, create_type=False)


def _staging_common() -> list[sa.Column]:
    """Columns every ``stg_*`` table carries: lineage back to the landing row."""
    return [
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column("generation", sa.Integer, nullable=False),
        sa.Column("source_id", sa.Text, nullable=False),
        sa.Column("source_ref", sa.Text, nullable=False),
        sa.Column("raw_record_id", sa.BigInteger, sa.ForeignKey("raw_records.id"), nullable=True),
        sa.Column("run_id", sa.Text, nullable=True),
        sa.Column("row_hash", sa.Text, nullable=False),
        sa.Column("materialized_at", TS, nullable=False, server_default=NOW),
    ]


def upgrade() -> None:
    bind = op.get_bind()

    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    for name, values in ENUMS:
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)

    _create_operational_tables()
    _create_staging_tables()
    _create_identity_tables()
    _create_review_tables()
    _create_incident_tables()
    _create_apply_path_trigger()


def downgrade() -> None:
    bind = op.get_bind()

    op.execute("DROP TRIGGER IF EXISTS entities_require_proposal_event ON entities")
    op.execute("DROP FUNCTION IF EXISTS keystone_require_proposal_event()")

    for table in TABLES:
        op.drop_table(table)

    for name, values in ENUMS:
        postgresql.ENUM(*values, name=name).drop(bind, checkfirst=True)

    op.execute("DROP EXTENSION IF EXISTS vector")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")


# --------------------------------------------------------------------------
# landing + per-source completeness
# --------------------------------------------------------------------------
def _create_operational_tables() -> None:
    op.create_table(
        "ingest_runs",
        sa.Column("run_id", sa.Text, nullable=False),
        sa.Column("source_id", sa.Text, nullable=False),
        sa.Column("generation", sa.Integer, nullable=False),
        sa.Column("status", _enum("ingest_status", INGEST_STATUS), nullable=False),
        sa.Column("started_at", TS, nullable=False, server_default=NOW),
        sa.Column("finished_at", TS, nullable=True),
        sa.Column("records_ok", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("records_rejected", sa.Integer, nullable=False, server_default=sa.text("0")),
        sa.Column("error_detail", JSONB, nullable=True),
        sa.PrimaryKeyConstraint("run_id", "source_id", name="pk_ingest_runs"),
        sa.CheckConstraint("records_ok >= 0", name="ck_ingest_runs_ok_nonneg"),
        sa.CheckConstraint("records_rejected >= 0", name="ck_ingest_runs_rejected_nonneg"),
        comment=(
            "Per-source completeness for a generation. Absence-style invariants "
            "(C5/C8) MUST be skipped for a source whose run is not 'ok' -- this "
            "table is what makes that decision, so it is load-bearing, not logging."
        ),
    )
    op.create_index(
        "ix_ingest_runs_source_generation", "ingest_runs", ["source_id", "generation", "status"]
    )

    op.create_table(
        "raw_records",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column("source_id", sa.Text, nullable=False),
        sa.Column("entity_type", sa.Text, nullable=False),
        sa.Column("natural_key", sa.Text, nullable=False),
        sa.Column("generation", sa.Integer, nullable=False),
        sa.Column("payload", JSONB, nullable=False),
        sa.Column("row_hash", sa.Text, nullable=False),
        sa.Column("load_id", sa.Text, nullable=False),
        sa.Column("run_id", sa.Text, nullable=True),
        sa.Column("ingest_ts", TS, nullable=False, server_default=NOW),
        comment=(
            "Append-only landing table. Duplicate natural keys within a "
            "generation are legitimate input (C11) and are NOT deduplicated here."
        ),
    )
    op.create_index(
        "ix_raw_records_source_key",
        "raw_records",
        ["source_id", "entity_type", "natural_key", "generation"],
    )
    op.create_index("ix_raw_records_generation", "raw_records", ["generation"])
    op.create_index("ix_raw_records_row_hash", "raw_records", ["row_hash"])


# --------------------------------------------------------------------------
# normalized staging -- Python materializes, SQL only reads
# --------------------------------------------------------------------------
def _create_staging_tables() -> None:
    op.create_table(
        "stg_crm_contact",
        *_staging_common(),
        sa.Column("crm_id", sa.Text, nullable=False),
        sa.Column("email", sa.Text, nullable=True),
        sa.Column("first_name", sa.Text, nullable=True),
        sa.Column("last_name", sa.Text, nullable=True),
        sa.Column("lifecycle_stage", sa.Text, nullable=True),
        sa.Column("external_id", sa.Text, nullable=True),
        sa.Column("dob", sa.Text, nullable=True),
        sa.Column("grade", sa.Text, nullable=True),
        sa.Column("state", sa.Text, nullable=True),
        sa.Column("marketing_consent", sa.Boolean, nullable=True),
        sa.Column("created_at", TS, nullable=True),
        sa.Column("updated_at", TS, nullable=True),
        sa.Column("email_norm", sa.Text, nullable=True),
        sa.Column("first_norm", sa.Text, nullable=True),
        sa.Column("last_norm", sa.Text, nullable=True),
        sa.Column("dob_norm", sa.Date, nullable=True),
        sa.Column("grade_norm", sa.Text, nullable=True),
        sa.Column("grade_ord", sa.Integer, nullable=True),
        sa.Column("state_norm", sa.Text, nullable=True),
        sa.Column("lifecycle_norm", sa.Text, nullable=True),
        sa.Column("unchecked_fields", JSONB, nullable=True),
        comment="Normalized CRM contacts. rules/*.sql read *_norm only; they never normalize.",
    )
    op.create_index("ix_stg_crm_contact_natural", "stg_crm_contact", ["generation", "crm_id"])
    op.create_index("ix_stg_crm_contact_email", "stg_crm_contact", ["generation", "email_norm"])
    op.create_index(
        "ix_stg_crm_contact_namedob",
        "stg_crm_contact",
        ["generation", "first_norm", "last_norm", "dob_norm"],
    )
    op.create_index("ix_stg_crm_contact_ext", "stg_crm_contact", ["generation", "external_id"])

    op.create_table(
        "stg_crm_deal",
        *_staging_common(),
        sa.Column("deal_id", sa.Text, nullable=False),
        sa.Column("name", sa.Text, nullable=True),
        sa.Column("pipeline", sa.Text, nullable=True),
        sa.Column("stage", sa.Text, nullable=True),
        sa.Column("amount_raw", sa.Text, nullable=True),
        sa.Column("associated_contact_ids", JSONB, nullable=True),
        sa.Column("created_at", TS, nullable=True),
        sa.Column("updated_at", TS, nullable=True),
        sa.Column("amount_cents", sa.BigInteger, nullable=True),
        sa.Column(
            "amount_microusd",
            sa.BigInteger,
            sa.Computed("amount_cents * 10000", persisted=True),
            nullable=True,
        ),
        sa.Column("stage_funnel", sa.Text, nullable=True),
        sa.Column("stage_funnel_ord", sa.Integer, nullable=True),
        sa.Column("pipeline_norm", sa.Text, nullable=True),
        sa.Column("unchecked_fields", JSONB, nullable=True),
        comment=(
            "Normalized CRM deals. `amount` is CRM-shaped float in the source; it "
            "is retained verbatim as text and normalized to integer cents."
        ),
    )
    op.create_index("ix_stg_crm_deal_natural", "stg_crm_deal", ["generation", "deal_id"])
    op.create_index("ix_stg_crm_deal_stage", "stg_crm_deal", ["generation", "stage_funnel"])
    op.create_index(
        "ix_stg_crm_deal_contacts",
        "stg_crm_deal",
        ["associated_contact_ids"],
        postgresql_using="gin",
    )

    op.create_table(
        "stg_student",
        *_staging_common(),
        sa.Column("student_id", sa.Text, nullable=False),
        sa.Column("first_name", sa.Text, nullable=True),
        sa.Column("last_name", sa.Text, nullable=True),
        sa.Column("dob", sa.Text, nullable=True),
        sa.Column("grade", sa.Text, nullable=True),
        sa.Column("guardian_email", sa.Text, nullable=True),
        sa.Column("guardian2_email", sa.Text, nullable=True),
        sa.Column("status", sa.Text, nullable=True),
        sa.Column("enrollment_year", sa.Integer, nullable=True),
        sa.Column("student_number", sa.Text, nullable=True),
        sa.Column("household_id", sa.Text, nullable=True),
        sa.Column("communication_opt_out", sa.Boolean, nullable=True),
        sa.Column("created_at", TS, nullable=True),
        sa.Column("updated_at", TS, nullable=True),
        sa.Column("email_norm", sa.Text, nullable=True),
        sa.Column("guardian2_email_norm", sa.Text, nullable=True),
        sa.Column("first_norm", sa.Text, nullable=True),
        sa.Column("last_norm", sa.Text, nullable=True),
        sa.Column("dob_norm", sa.Date, nullable=True),
        sa.Column("grade_norm", sa.Text, nullable=True),
        sa.Column("grade_ord", sa.Integer, nullable=True),
        sa.Column("status_norm", sa.Text, nullable=True),
        sa.Column("status_compare", sa.Text, nullable=True),
        sa.Column("unchecked_fields", JSONB, nullable=True),
        comment=(
            "Normalized app-DB students. `email_norm` is the normalized primary "
            "guardian email; `status_compare` folds 'active' into 'enrolled'."
        ),
    )
    op.create_index("ix_stg_student_natural", "stg_student", ["generation", "student_id"])
    op.create_index("ix_stg_student_email", "stg_student", ["generation", "email_norm"])
    op.create_index(
        "ix_stg_student_guardian2", "stg_student", ["generation", "guardian2_email_norm"]
    )
    op.create_index(
        "ix_stg_student_namedob",
        "stg_student",
        ["generation", "first_norm", "last_norm", "dob_norm"],
    )
    op.create_index("ix_stg_student_number", "stg_student", ["generation", "student_number"])
    op.create_index("ix_stg_student_household", "stg_student", ["generation", "household_id"])

    op.create_table(
        "stg_enrollment",
        *_staging_common(),
        sa.Column("enrollment_id", sa.Text, nullable=False),
        sa.Column("student_id", sa.Text, nullable=True),
        sa.Column("program", sa.Text, nullable=True),
        sa.Column("stage", sa.Text, nullable=True),
        sa.Column("deposit_paid_at", TS, nullable=True),
        sa.Column("crm_deal_id", sa.Text, nullable=True),
        sa.Column("billing_owner_email", sa.Text, nullable=True),
        sa.Column("created_at", TS, nullable=True),
        sa.Column("updated_at", TS, nullable=True),
        sa.Column("stage_funnel", sa.Text, nullable=True),
        sa.Column("stage_funnel_ord", sa.Integer, nullable=True),
        sa.Column("program_norm", sa.Text, nullable=True),
        sa.Column("billing_owner_email_norm", sa.Text, nullable=True),
        sa.Column("unchecked_fields", JSONB, nullable=True),
        comment="Normalized app-DB enrollments; stage_funnel is the canonical funnel token.",
    )
    op.create_index("ix_stg_enrollment_natural", "stg_enrollment", ["generation", "enrollment_id"])
    op.create_index("ix_stg_enrollment_student", "stg_enrollment", ["generation", "student_id"])
    op.create_index("ix_stg_enrollment_deal", "stg_enrollment", ["generation", "crm_deal_id"])
    op.create_index("ix_stg_enrollment_stage", "stg_enrollment", ["generation", "stage_funnel"])

    op.create_table(
        "stg_payment",
        *_staging_common(),
        sa.Column("payment_id", sa.Text, nullable=False),
        sa.Column("payer_email", sa.Text, nullable=True),
        sa.Column("payer_name", sa.Text, nullable=True),
        sa.Column("amount_cents", sa.BigInteger, nullable=True),
        sa.Column("currency", sa.Text, nullable=True),
        sa.Column("type", sa.Text, nullable=True),
        sa.Column("status", sa.Text, nullable=True),
        sa.Column("occurred_at", TS, nullable=True),
        sa.Column("refunded_at", TS, nullable=True),
        sa.Column("external_ref", sa.Text, nullable=True),
        sa.Column("payment_metadata", JSONB, nullable=True),
        sa.Column(
            "amount_microusd",
            sa.BigInteger,
            sa.Computed("amount_cents * 10000", persisted=True),
            nullable=True,
        ),
        sa.Column("email_norm", sa.Text, nullable=True),
        sa.Column(
            "payer_email_norm",
            sa.Text,
            sa.Computed("email_norm", persisted=True),
            nullable=True,
        ),
        sa.Column("payer_first_norm", sa.Text, nullable=True),
        sa.Column("payer_last_norm", sa.Text, nullable=True),
        sa.Column("student_name_first_norm", sa.Text, nullable=True),
        sa.Column("student_name_last_norm", sa.Text, nullable=True),
        sa.Column("program_norm", sa.Text, nullable=True),
        sa.Column("type_norm", sa.Text, nullable=True),
        sa.Column("status_norm", sa.Text, nullable=True),
        sa.Column("unchecked_fields", JSONB, nullable=True),
        comment=(
            "Normalized payments. `payer_email_norm` is a stored generated mirror "
            "of `email_norm` so the conflict catalogue's column name and the "
            "uniform staging column name can never disagree."
        ),
    )
    op.create_index("ix_stg_payment_natural", "stg_payment", ["generation", "payment_id"])
    op.create_index("ix_stg_payment_email", "stg_payment", ["generation", "email_norm"])
    op.create_index("ix_stg_payment_ext", "stg_payment", ["generation", "external_ref"])
    op.create_index(
        "ix_stg_payment_dupe",
        "stg_payment",
        ["generation", "email_norm", "amount_cents", "type_norm", "occurred_at"],
    )


# --------------------------------------------------------------------------
# identity / canonical layer
# --------------------------------------------------------------------------
def _create_identity_tables() -> None:
    op.create_table(
        "entities",
        sa.Column("canonical_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("entity_type", sa.Text, nullable=False),
        sa.Column("current", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.Column("updated_at", TS, nullable=False, server_default=NOW),
        comment=(
            "CANONICAL table. Only `apply_writer` may INSERT/UPDATE it, and an "
            "UPDATE must be accompanied by a proposal_events row in the same "
            "transaction (trigger entities_require_proposal_event)."
        ),
    )
    op.create_index("ix_entities_type", "entities", ["entity_type"])

    op.create_table(
        "entity_links",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column("canonical_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_id", sa.Text, nullable=False),
        sa.Column("source_key", sa.Text, nullable=False),
        sa.Column("source_ref", sa.Text, nullable=False),
        sa.Column("method", sa.Text, nullable=False),
        sa.Column("generation", sa.Integer, nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.UniqueConstraint(
            "generation", "source_id", "source_key", name="uq_entity_links_source_generation"
        ),
        comment=(
            "The WINNING link chosen by the ER cascade, one per source ref per "
            "generation. Every considered resolution -- including discarded ones "
            "-- lives in entity_link_candidates."
        ),
    )
    op.create_index("ix_entity_links_canonical", "entity_links", ["canonical_id", "generation"])
    op.create_index("ix_entity_links_ref", "entity_links", ["generation", "source_ref"])

    op.create_table(
        "entity_link_candidates",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column("source_ref", sa.Text, nullable=False),
        sa.Column("key_class", sa.Text, nullable=False),
        sa.Column("resolved_ref", sa.Text, nullable=False),
        sa.Column("generation", sa.Integer, nullable=False),
        sa.Column("rule", sa.Text, nullable=True),
        sa.Column("accepted", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("detail", JSONB, nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        comment=(
            "EVERY match-key resolution, accepted or discarded. R-010 "
            "(merge-collapsed record) reads the discarded rows -- one contact "
            "whose 'ext' key and 'namedob' key resolve to two different students "
            "-- so discarded candidates must be retained, never overwritten."
        ),
    )
    op.create_index(
        "ix_link_candidates_source", "entity_link_candidates", ["generation", "source_ref"]
    )
    op.create_index(
        "ix_link_candidates_resolved",
        "entity_link_candidates",
        ["generation", "key_class", "resolved_ref"],
    )
    op.create_index(
        "ix_link_candidates_accepted",
        "entity_link_candidates",
        ["generation", "source_ref", "key_class"],
        postgresql_where=sa.text("NOT accepted"),
    )

    op.create_table(
        "field_lineage",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column("canonical_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("field", sa.Text, nullable=False),
        sa.Column("value_text", sa.Text, nullable=True),
        sa.Column("source_id", sa.Text, nullable=False),
        sa.Column("source_ref", sa.Text, nullable=True),
        sa.Column("generation", sa.Integer, nullable=False),
        sa.Column("observed_ts", TS, nullable=False, server_default=NOW),
        comment="All generations retained: oscillation (A,B,A) is a window scan over this table.",
    )
    op.create_index(
        "ix_field_lineage_scan", "field_lineage", ["canonical_id", "field", "generation"]
    )


# --------------------------------------------------------------------------
# invariants, conflicts, proposals, budget, audit, clients
# --------------------------------------------------------------------------
def _create_review_tables() -> None:
    op.create_table(
        "invariant_results",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column("run_id", sa.Text, nullable=False),
        sa.Column("rule_id", sa.Text, nullable=False),
        sa.Column("rule_version", sa.Text, nullable=False),
        sa.Column("record_ref", sa.Text, nullable=False),
        sa.Column("entity_type", sa.Text, nullable=False),
        sa.Column("verdict", _enum("invariant_verdict", INVARIANT_VERDICT), nullable=False),
        sa.Column("detail", JSONB, nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        comment="Per-record verdicts are the grading contract; rows are never overwritten per run.",
    )
    op.create_index("ix_invariant_results_run", "invariant_results", ["run_id", "rule_id"])
    op.create_index("ix_invariant_results_ref", "invariant_results", ["record_ref", "run_id"])
    op.create_index("ix_invariant_results_verdict", "invariant_results", ["run_id", "verdict"])

    op.create_table(
        "conflicts",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column("fingerprint", sa.Text, nullable=False),
        sa.Column("type", sa.Text, nullable=False),
        sa.Column("rule_id", sa.Text, nullable=True),
        sa.Column("entity_refs", JSONB, nullable=False),
        sa.Column("sources", JSONB, nullable=False),
        sa.Column("disagreeing_fields", JSONB, nullable=False),
        sa.Column("observed_values", JSONB, nullable=True),
        sa.Column(
            "status",
            _enum("conflict_status", CONFLICT_STATUS),
            nullable=False,
            server_default=sa.text("'open'::conflict_status"),
        ),
        sa.Column("escalation_reason", sa.Text, nullable=True),
        sa.Column("oscillating", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("first_seen_run", sa.Text, nullable=False),
        sa.Column("last_seen_run", sa.Text, nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.UniqueConstraint("fingerprint", name="uq_conflicts_fingerprint"),
        comment=(
            "fingerprint = sha256(type | sorted(entity_refs) | sorted(fields) | "
            "sorted(observed_values)); UNIQUE is what makes re-detection idempotent."
        ),
    )
    op.create_index("ix_conflicts_type_status", "conflicts", ["type", "status"])
    op.create_index("ix_conflicts_last_seen", "conflicts", ["last_seen_run"])

    op.create_table(
        "proposals",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column("conflict_id", sa.BigInteger, sa.ForeignKey("conflicts.id"), nullable=False),
        sa.Column("fingerprint", sa.Text, nullable=False),
        sa.Column("action", JSONB, nullable=False),
        sa.Column("confidence", sa.Numeric(5, 4), nullable=False),
        sa.Column("evidence", JSONB, nullable=False),
        sa.Column("rationale", sa.Text, nullable=True),
        sa.Column(
            "status",
            _enum("proposal_status", PROPOSAL_STATUS),
            nullable=False,
            server_default=sa.text("'pending'::proposal_status"),
        ),
        sa.Column("sensitive", sa.Boolean, nullable=False, server_default=sa.text("false")),
        sa.Column("created_run", sa.Text, nullable=False),
        sa.Column("decided_by", sa.Text, nullable=True),
        sa.Column("decided_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_proposals_confidence_range"
        ),
        sa.CheckConstraint(
            "NOT (sensitive AND status = 'applied'::proposal_status AND decided_by IS NULL)",
            name="ck_proposals_sensitive_never_auto_applied",
        ),
        comment=(
            "Proposals land 'pending' or 'sensitive_hold'; nothing here writes a "
            "source or the canonical layer. Confidence is exact numeric, not float."
        ),
    )
    op.create_index(
        "uq_proposals_open_fingerprint",
        "proposals",
        ["fingerprint"],
        unique=True,
        postgresql_where=sa.text("status <> 'rejected'::proposal_status"),
    )
    op.create_index("ix_proposals_status", "proposals", ["status", "created_at"])
    op.create_index("ix_proposals_conflict", "proposals", ["conflict_id"])

    op.create_table(
        "proposal_events",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column("proposal_id", sa.BigInteger, sa.ForeignKey("proposals.id"), nullable=False),
        sa.Column("event", sa.Text, nullable=False),
        sa.Column("before", JSONB, nullable=True),
        sa.Column("after", JSONB, nullable=True),
        sa.Column("actor", sa.Text, nullable=False),
        sa.Column("ts", TS, nullable=False, server_default=NOW),
        sa.Column(
            "txid",
            sa.BigInteger,
            nullable=False,
            server_default=sa.text("pg_current_xact_id()::text::bigint"),
        ),
        comment=(
            "The rollback path. `txid` records the writing transaction so the "
            "entities trigger can prove the reversal record was written in the "
            "SAME transaction as the canonical write."
        ),
    )
    op.create_index("ix_proposal_events_proposal", "proposal_events", ["proposal_id", "ts"])
    op.create_index("ix_proposal_events_txid", "proposal_events", ["txid"])

    op.create_table(
        "budget_ledger",
        sa.Column("scope", sa.Text, primary_key=True),
        sa.Column("cap_microusd", sa.BigInteger, nullable=False),
        sa.Column("spent_microusd", sa.BigInteger, nullable=False, server_default=sa.text("0")),
        sa.Column("updated_at", TS, nullable=False, server_default=NOW),
        sa.CheckConstraint("cap_microusd >= 0", name="ck_budget_cap_nonneg"),
        sa.CheckConstraint("spent_microusd >= 0", name="ck_budget_spent_nonneg"),
        sa.CheckConstraint("spent_microusd <= cap_microusd", name="ck_budget_spent_within_cap"),
        comment=(
            "Money is integer microusd, never float. The cap CHECK is the backstop "
            "under the atomic reserve-then-settle UPDATE, not a substitute for it."
        ),
    )

    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column("ts", TS, nullable=False, server_default=NOW),
        sa.Column("actor", sa.Text, nullable=False),
        sa.Column("action", sa.Text, nullable=False),
        sa.Column("subject", sa.Text, nullable=True),
        sa.Column("detail", JSONB, nullable=True),
        sa.Column("tokens_in", sa.Integer, nullable=True),
        sa.Column("tokens_out", sa.Integer, nullable=True),
        sa.Column("cost_microusd", sa.BigInteger, nullable=True),
        sa.CheckConstraint(
            "cost_microusd IS NULL OR cost_microusd >= 0", name="ck_audit_cost_nonneg"
        ),
        comment="LOG_MODE=safe stores hash+preview in `detail`; LOG_MODE=full stores raw detail.",
    )
    op.create_index("ix_audit_log_ts", "audit_log", ["ts"])
    op.create_index("ix_audit_log_action", "audit_log", ["action", "ts"])

    op.create_table(
        "api_clients",
        sa.Column("key_hash", sa.Text, primary_key=True),
        sa.Column("scope", _enum("api_client_scope", API_CLIENT_SCOPE), nullable=False),
        sa.Column("label", sa.Text, nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.CheckConstraint("key_hash ~ '^[0-9a-f]{64}$'", name="ck_api_clients_hash_is_sha256_hex"),
        comment=(
            "Only sha256(salt:key) hex ever lands here; the CHECK makes storing a "
            "plaintext key structurally impossible."
        ),
    )


def _create_incident_tables() -> None:
    op.create_table(
        "incidents",
        sa.Column("id", sa.BigInteger, sa.Identity(), primary_key=True),
        sa.Column("centroid", Vector(), nullable=True),
        sa.Column("label", sa.Text, nullable=False),
        sa.Column("embedding_model", sa.Text, nullable=True),
        sa.Column("embedding_dim", sa.Integer, nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        comment=(
            "pgvector incident clusters (stretch #8). Dimension follows the embedding provider."
        ),
    )

    op.create_table(
        "conflict_incidents",
        sa.Column("incident_id", sa.BigInteger, sa.ForeignKey("incidents.id"), nullable=False),
        sa.Column("conflict_id", sa.BigInteger, sa.ForeignKey("conflicts.id"), nullable=False),
        sa.Column("distance", sa.Numeric(10, 8), nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=NOW),
        sa.PrimaryKeyConstraint("incident_id", "conflict_id", name="pk_conflict_incidents"),
    )
    op.create_index("ix_conflict_incidents_conflict", "conflict_incidents", ["conflict_id"])


# --------------------------------------------------------------------------
# apply-path enforcement
# --------------------------------------------------------------------------
def _create_apply_path_trigger() -> None:
    """Canonical UPDATE requires a same-transaction proposal_events row.

    Deferred to commit so the apply function may write the canonical row and
    the reversal record in either order within one transaction. SQLSTATE
    ``KS001`` is deliberately distinct from any built-in class so a test can
    assert on it and cannot pass on an unrelated error.
    """
    op.execute(
        """
        CREATE FUNCTION keystone_require_proposal_event() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM proposal_events
                WHERE txid = pg_current_xact_id()::text::bigint
            ) THEN
                RAISE EXCEPTION
                    'canonical UPDATE on entities requires a proposal_events row in the '
                    'same transaction (holds-before-writes)'
                    USING ERRCODE = 'KS001';
            END IF;
            RETURN NULL;
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER entities_require_proposal_event
        AFTER UPDATE ON entities
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION keystone_require_proposal_event();
        """
    )
